### ISSUE TITLE
增加一个一键跳到100%进度的脚本

### ISSUE THREAD

**Issue by TakiVotoid** [DDoSolitary/gxb-buaa73#1]
https://paste.ubuntu.com/p/YCMqhTNVmS/
直接按F12粘到console里也行，
搭配TamperMonkey效果更佳~

**Comment by DDoSolitary** [comment]
嗯看了下，方法和我昨天尝试的一样，但是我昨天试的时候没有效果，可能是之前我一直16倍速播放的后遗症。
今天困死了，等我明天改一改代码风格再加上去

**Comment by TakiVotoid** [comment]
（这边chrome亲测有效~）
time那个地方或许可以再处理一下~寻思了一下这项可能是post过去的时间，姑且考虑的是post一个假时间，以免密集post会被发现&勒令退学23333333
（不过感觉上好像这课水了就水了问题不大）

**Comment by TakiVotoid** [comment]
（这边chrome亲测有效~）
time那个地方或许可以再处理一下寻思了一下这项可能是post过去的时间，姑且考虑的是post一个假时间，以免密集post会被发现&勒令退学23333333
（不过感觉上好像这课水了就水了问题不大）
dalao加油

**Comment by DDoSolitary** [comment]
我看过网页代码这个确实是时间，原代码写的是`(new Date).getTime()`
我觉得这个post的时间用处最多用于log和debug之类的，我之前曾经尝试再别的api里不放这个时间，一样能正常使用
真的要查的话不是看看谁看视频看的最快就好了（手动滑稽

**Comment by DDoSolitary** [comment]
我好像明白为什么我之前的方法不行了。我原来是把`ch`和`mh`都设置为视频时长，这个脚本是把`mh`设置为当前实际的观看进度，然后就绕过了服务器的检测

**Comment by DDoSolitary** [comment]
经测试只要把mh设置成0好像就可以了，url里的和post数据里的时间都不发也没有关系，甚至rl不发也没有关系，这些东西应该都是仅用于log的
