### ISSUE TITLE
批量完成会出事嘛

### ISSUE THREAD

**Issue by shreksG** [DDoSolitary/gxb-buaa73#6]

**Comment by DDoSolitary** [comment]
只能说有可能会有可能不会，因为我也不知道他们服务器端的代码具体是怎么写的
我自己的全都是用脚本批量完成的，一点事都没有
另外我记的有一个同学用脚本没有效果，反而用了以后正常播放也不计算进度了，但是后来好像又恢复正常了
自己斟酌吧。。

**Comment by shreksG** [comment]
谢谢大佬，批量完成很强。
